click_radius = 30
min_drag_distance = 10
drag_start_timer = 0.5
default_fov = 3000
min_fov = 500
max_fov = 4000
zoom_speed = 1.01
crab_speed = 100
road_node_ui_radius = 20
animation_speed = 10
jump_height = 10
jump_rotation_amplitude = 0.1
collision_check_distance = 50
collision_check_radius = 50
collision_slow_down = 2
crabs = 100
free_items = 20
crab_left_hand_pos = [-50, 10]
crab_right_hand_pos = [50, 10]
crab_hold_item_probability = 0.2
crab_hold_double_item_probability = 0.1
types_to_find = 3
